# Generated by Django 2.2 on 2019-06-17 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressee', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=50)),
                ('suite', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state_abbreviation', models.CharField(max_length=2)),
                ('zip_code', models.DecimalField(decimal_places=0, max_digits=5)),
                ('Store', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'ordering': ['addressee'],
            },
        ),
        migrations.CreateModel(
            name='GroceryStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.ForeignKey(limit_choices_to={'Store': True}, on_delete=django.db.models.deletion.CASCADE, to='homepage.Address')),
            ],
            options={
                'verbose_name_plural': 'Grocery Stores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('stock', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Inventory',
                'ordering': ['store', 'item'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('delivery_choice', models.CharField(choices=[('P', 'Pickup'), ('D', 'Delivery')], max_length=1)),
                ('delivery_address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Address')),
                ('ordered_inventory', models.ManyToManyField(to='homepage.Inventory')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Item'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.GroceryStore'),
        ),
    ]
